# cloudbuild.yaml
# Substitutions: override in trigger or with gcloud builds submit
substitutions:
  _REGION: "us-central1"
  _REPO: "dotnet10-gcp-cloudrun"
  _IMAGE: "dotnet10-gcp-cloudrun-img"
  _SERVICE: "dotnet10-gcp-cloudrun-api"

steps:
- name: 'gcr.io/cloud-builders/docker'
  args:
    - 'build'
    - '-t'
    - '${_REGION}-docker.pkg.dev/${PROJECT_ID}/${_REPO}/${_IMAGE}:${SHORT_SHA}'
    - '.'

- name: 'gcr.io/cloud-builders/docker'
  args:
    - 'push'
    - '${_REGION}-docker.pkg.dev/${PROJECT_ID}/${_REPO}/${_IMAGE}:${SHORT_SHA}'

- name: 'gcr.io/google.com/cloudsdktool/cloud-sdk'
  entrypoint: 'bash'
  args:
    - '-c'
    - |
      gcloud run deploy "${_SERVICE}" \
        --image "${_REGION}-docker.pkg.dev/${PROJECT_ID}/${_REPO}/${_IMAGE}:${SHORT_SHA}" \
        --region "${_REGION}" \
        --platform managed \
        --allow-unauthenticated \
        --set-secrets SWAGGER_AUTH_PASSWORD=swagger-password:1 \
        --quiet

images:
- '${_REGION}-docker.pkg.dev/${PROJECT_ID}/${_REPO}/${_IMAGE}:${SHORT_SHA}'
